pipeline {
    agent { label 'worker' }

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
        WEBSERVER_HOSTNAME = "webserver.server.cx.ua"
        CONTAINER_NAME = "simple-webapp"
        DOCKER_IMAGE = "13rom/simple-webapp"
        IMAGE_TAG = "0.2.${BUILD_NUMBER}"
    }

    stages {
        stage('Git Checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/ansible']], extensions: [], userRemoteConfigs: [[credentialsId: 'github', url: 'git@github.com:13rom/sample-webapp.git']])
            }
        }

        stage('Compile') {
            steps {
                dir('springbootapp') {
                    sh 'sed -i "s/%DATE%/$(date)/" src/main/java/com/example/demo/FinalProjectDemoApplication.java'
                    sh 'sed -i "s/%BUILD%/${BUILD_NUMBER}/" src/main/java/com/example/demo/FinalProjectDemoApplication.java'
                }
            }
        }

        stage('Build Image') {
            steps {
                dir('springbootapp'){
                    script {
                        dockerImage = docker.build DOCKER_IMAGE + ":$IMAGE_TAG"
                    }
                }
            }
        }

        stage('Push Image') {
            steps {
                script {
                    docker.withRegistry('', 'dockerhub') {
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }

        stage('Deploy') {
            steps{
                dir('springbootapp/ansible') {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                        sh 'cat hosts.ini'
                        sh 'ansible -i hosts.ini all -m ping'
                        sh 'ansible-playbook deploy.yaml --extra-vars "DOCKER_USERNAME=${DOCKER_USERNAME} DOCKER_PASSWORD=${DOCKER_PASSWORD}"'
                    }
                }
            }
        }
    }


    post {
        always {
            echo "Cleaning up slave docker..."
            sh 'docker logout'
            sh "docker rmi ${DOCKER_IMAGE}:${IMAGE_TAG}"
        }
    }
}
