# docker-compose.yaml
# Use to deploy a container in a docker swarm stack
# with zero-downtime.
#
# Usage:
#       $ IMAGE=13rom/simple-webapp:0.2.4 docker stack deploy -c docker-compose.yaml demo --with-registry-auth

version: "3.7"

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - webapp
    restart: always
    environment:
      DOMAINS: 'webserver.server.cx.ua -> http://webapp:8080'
      STAGE: 'production'
      # FORCE_RENEW: 'true'
    volumes:
      - https-portal-data:/var/lib/https-portal
    depends_on:
      - webapp

  webapp:
    image: ${IMAGE}
    # image: 13rom/simple-webapp:0.2.6
    hostname: virtual-server
    ports:
      - '8080:8080'
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8080 || exit 1"
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 5s
      rollback_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  https-portal-data:
